id: A6446BB64
title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good Actions”
  (Zangchö Mönlam)'
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:06:36.003120
  last_modified_at: 2022-03-01 03:06:36.003123
