id: A6446BB64
title: Praise of the Twelve Acts of the Buddha
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:06:35.987021
  last_modified_at: 2022-03-01 03:06:35.987023
