id: A6446BB64
title: Verses of Homage to the Buddhas and Bodhisattvas Together with their Mantras
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:06:36.013964
  last_modified_at: 2022-03-01 03:06:36.013967
