id: A6446BB64
title: Verses on the Buddha's Previous Lives
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:06:36.015649
  last_modified_at: 2022-03-01 03:06:36.015652
