id: A6446BB64
title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:06:36.010474
  last_modified_at: 2022-03-01 03:06:36.010477
